services:
  nodecg:
    image: node:20
    container_name: abw_nodecg
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: npm run dev
    env_file:
      - .env
    ports:
      - "${NODECG_PORT}:9092"
